# Generated by Django 4.1.1 on 2022-09-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_auto_20200908_1628"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["created_at"], "verbose_name_plural": "People"},
        ),
    ]
